module.exports = {
  CONTAINER_POLICY: {
    content: [
      'tabview',
      'multifield',
      'fieldset',
      'group:Standard',
      'group:Resource',
      'group:Selection',
      'group:Authoring Helper',
      'helloworld',
      'trophyfield',
    ],
    tabs: [
      'tab',
    ],
    tabcontent: [
      'multifield',
      'fieldset',
      'group:Standard',
      'group:Resource',
      'group:Selection',
      'group:Authoring Helper',
      'helloworld',
      'trophyfield',
    ],
    mf: [
      'textfield',
      'hidden',
      'datepicker',
      'checkbox',
      'radio',
      'select',
      'pathfield',
      'multifield',
      'fieldset',
      'group:Standard',
      'group:Resource',
      'group:Selection',
      'group:Authoring Helper',
    ],
    fs: [
      'multifield',
      'fieldset',
      'group:Standard',
      'group:Resource',
      'group:Selection',
      'group:Authoring Helper',
      'helloworld',
      'trophyfield',
    ],
  },
};
